ignore:
 - "tests"
 - "src/testing"
 - "perf"
 - "**/*_test.c"
 - "**/cJSON.c"
coverage:
 range: 50..95
 status:
  patch: false
  project:
    default:
      # basic
      target: auto
      threshold: 5%
      base: auto
      if_ci_failed: success