if(CONFIG_NANONNG)
  set(NNG_PLATFORM_POSIX ON CACHE BOOL "" FORCE)
  set(NNG_PLATFORM_ZEPHYR ON CACHE BOOL "" FORCE)
  set(NNG_STATIC_LIB ON CACHE BOOL "" FORCE)
  set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
  set(NNG_TESTS OFF CACHE BOOL "" FORCE)
  set(NNG_TOOLS OFF CACHE BOOL "" FORCE)
  set(NNG_ENABLE_NNGCAT OFF CACHE BOOL "" FORCE)
  set(NNG_ENABLE_COVERAGE OFF CACHE BOOL "" FORCE)
  set(NNG_ENABLE_TLS OFF CACHE BOOL "" FORCE)
  set(NNG_ENABLE_QUIC OFF CACHE BOOL "" FORCE)
  set(NNG_TRANSPORT_IPC OFF CACHE BOOL "" FORCE)
  set(NNG_TRANSPORT_TLS OFF CACHE BOOL "" FORCE)
  set(NNG_TRANSPORT_MQTT_TLS OFF CACHE BOOL "" FORCE)
  set(NNG_TRANSPORT_MQTT_BROKER_TLS OFF CACHE BOOL "" FORCE)
  set(NNG_ENABLE_HTTP ON CACHE BOOL "" FORCE)
  set(NNG_ENABLE_SQLITE OFF CACHE BOOL "" FORCE)
  set(NNG_ENABLE_COMPAT OFF CACHE BOOL "" FORCE)

  add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/.. ${PROJECT_BINARY_DIR}/nanonng_root)

  target_include_directories(nng PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/../include
    ${CMAKE_CURRENT_SOURCE_DIR}/../src/platform/zephyr/stubs
  )
  zephyr_link_libraries(nng)
endif()
