#
# Copyright 2026 Liebherr-Digital Development Center (LDC) <peter.bestler@liebherr.de>
#
# This software is supplied under the terms of the MIT License, a
# copy of which should be located in the distribution where this
# file was obtained (LICENSE.txt).  A copy of the license may also be
# found online at https://opensource.org/licenses/MIT.
#

listeners.ssl {
	bind = "tls+nmq-tcp://0.0.0.0:8883"
	keyfile = "pkcs11:token=NanoMQ;object=broker-key;type=private"
	certfile = "pkcs11:token=NanoMQ;object=broker-cert;type=cert"
	cacertfile = "pkcs11:token=NanoMQ;object=broker-ca;type=cert"
}
