[book]
authors = ["Garrett D'Amore"]
language = "en"
multilingual = false
src = "ref"
title = "NNG Reference Manual (DRAFT)"

[output.html]
smart-punctuation = true
fold.enable = true
fold.level = 2
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]
site-url = "/ref/"

[preprocessor.alerts]

[preprocessor.indexing]


# [preprocessor.inline-highlighting]
# default-language = "c"

[preprocessor.footnote]

[preprocessor.pagetoc]
